### ISSUE TITLE
Adding link to Blog Name 

### ISSUE THREAD

**Issue by atinder-harika** [AdityaInnovates/SimpleBlogApp#23]
**Issue Type**:  Bug Fix

**Description**:
The only way to open a blog page from the blog face card is to either click on the picture or click on 'read more' button. While the name itself is underlined and the cursor changes to pointer you cannot open the blog when the name is clicked. This is a bad UI/UX, it can be fixed by adding the feature access blog through the name too.

### Steps to Reproduce (if applicable)
1.  Go over to my forked repository
2.  In the about section and in the commit message you will find the link to github page hosting the demo website
3.  Click on the link and test out the new feature

### Expected Behavior (if applicable)
I expected that the name would also open the blog but it did not

### Additional Information
@AdityaInnovates kindly assign me this issue with the hacktoberfest tag so I can start contributing here.

**Comment by AdityaInnovates** [comment]
Go for it 👍
