### ISSUE TITLE
[Feature]: Bookmarking Blogs

### ISSUE THREAD

**Issue by AdityaInnovates** [AdityaInnovates/SimpleBlogApp#3]
**Issue Type**: Feature Request

**Description**:
1. Add a bookmark button in the top-right corner of each card.
2. Save the blog ID when the button is clicked.
3. When the homepage loads, check which blogs are bookmarked and highlight the bookmark icon accordingly.
4. Create a new HTML file to display all user's bookmarked blogs.

**Comment by mitul-bhatia** [comment]
assign me this 
please
